/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as DirectionsRouteImport } from './routes/directions'
import { Route as IndexRouteImport } from './routes/index'

const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectionsRoute = DirectionsRouteImport.update({
  id: '/directions',
  path: '/directions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/directions': typeof DirectionsRoute
  '/ops': typeof OpsRoute
  '/safety': typeof SafetyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/directions': typeof DirectionsRoute
  '/ops': typeof OpsRoute
  '/safety': typeof SafetyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/directions': typeof DirectionsRoute
  '/ops': typeof OpsRoute
  '/safety': typeof SafetyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/directions' | '/ops' | '/safety'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/directions' | '/ops' | '/safety'
  id: '__root__' | '/' | '/directions' | '/ops' | '/safety'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DirectionsRoute: typeof DirectionsRoute
  OpsRoute: typeof OpsRoute
  SafetyRoute: typeof SafetyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directions': {
      id: '/directions'
      path: '/directions'
      fullPath: '/directions'
      preLoaderRoute: typeof DirectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DirectionsRoute: DirectionsRoute,
  OpsRoute: OpsRoute,
  SafetyRoute: SafetyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
